### PR TITLE
Dark Theme implementation 

### PR DESCRIPTION
**Pull request by gverni**
Implementation of a dark theme based on VSC palette. 

Currently implemented: 
* Background color
* Content and title text color
* Backdrop color

To do/check: 
- [x] Icons for different pop-up types
- [x] Input elements 
- [ ] Buttons (the current ones kinda fit nicely, but it can be improved)
- [x] Toast 
- [x] Close icon 
- [x] Validation message
- [x] Queues
- [ ] Other elements?

See more at https://github.com/sweetalert2/sweetalert2/issues/547

### CODE REVIEW

**Comment by limonte** [comment]
Good day @gverni 

This PR looks good so far!

---

PS. small detail related to your dev environment:

image

It's not the first time there are trailing spaces in your code, linters don't like them too much :)

If you're using VS Code there's the `files.trimTrailingWhitespace` setting for that, see my dotfiles for more details: https://github.com/limonte/dotfiles/blob/master/.config/Code/User/settings.json#L29

**Comment by gverni** [comment]
Thanks @limone! I use standardJS plugin and I assumed it was checking scss
as well... Which obviously is not supposed to do :smile: Thanks for sharing
your config!

**Comment by limonte** [comment]
Good day @gverni!

Do you need any help with this PR?

**Comment by gverni** [comment]
Good day to you @limonte. So sorry, I was taken by other things. I’ll finish this PR by end of this week if that’s ok?

**Comment by limonte** [comment]
Sure, no problem :+1:

**Comment by limonte** [comment]
Great work so far @gverni :muscle: 

Added https://github.com/sweetalert2/sweetalert2-themes/pull/2/commits/de8dd21106adaa04f50e68e544e02dc7a3a17d14 which depends on https://github.com/sweetalert2/sweetalert2/pull/1563

Please take a look.

**Comment by gverni** [comment]
@limonte I reverted the "permanent workaround" in https://github.com/sweetalert2/sweetalert2-themes/pull/2/commits/ecc791f4011253b1c18dd8794a6b60e487e1edfd. The reason is that without it this is what you get: 

image

The reason is that we are using the same background variable for all the input types. I think this is the right way of doing from a SCSS point of view, but in this specific case we need to differentiate between background for range / radio and checkbox and the other backgrounds. 

What do you think?

**Comment by gverni** [comment]
@limonte I can't think of any other elements that needs the theme to be applied to. I didn't change the color of the buttons because I think they fit nicely. What do you think overall? Is there anything missing?

**Comment by limonte** [comment]
Parcel demo switched to the Dark Side of SweetAlert2: https://github.com/sweetalert2/sweetalert2-parcel-demo

**Comment by limonte** [comment]
https://www.jsdelivr.com/package/npm/@sweetalert2/themes

people are starting to use the Dark theme already :tada: 

image

**Pull request merged**
