### PR TITLE
Material UI implementation

### LINKED ISSUE #14: Material UI theme
Specs: https://next.material-ui.com/demos/dialogs/

The theme name should be `material-ui`

### PR DESCRIPTION
**Pull request by gverni**
Material UI theme implementation. Feel free to contribute. 

TODO / check

- [x] Confirm button
- [x] Cancel button
- [x] ~~Icons for different pop-up types~~: No changes
- [x] [Textbox](https://material.io/design/components/text-fields.html): no changes (_outlined_ style with round corners and no label). We may just look into make the validation error change color of the input (but that may require changes to Swal2 js)
- [x] [Select](https://material-components.github.io/material-components-web-catalog/#/component/select): implemented with CSS background image. To be _visually_ tested on different browsers
- [x] Radio
- [x] Checkbox 
- [x] ~~File~~: No changes 
- [x] [Range](https://material.io/design/components/sliders.html#https://material.io/design/components/sliders.html) 
- [x] Toast 
- [x] Close icon 
- [x] ~~Validation message~~: No changes
- [x] ~~Queues~~: No changes
- [x] Action buttons focus

Close #14

### CODE REVIEW

**Comment by gverni** [comment]
I've been _wrestling_ with the close button for the past couple of days. Unfortunately when the `font-size` is increased, the `&times;` character moves slightly down and that's what you get when you hover on the close button: 

image
(the X is not centred) 

I don't really like the effect, so I may drop completely the hover style (need to check if this is mandatory on _material_) or replace the `&times;` with an SVG. @limonte would you be in favour of this latter (i.e. use SVG for close button)?

**Comment by limonte** [comment]
> I don't really like the effect, so I may drop completely the hover style (need to check if this is mandatory on material) or replace the &times; with an SVG. @limonte would you be in favour of this latter (i.e. use SVG for close button)?

Thanks for bringing this up @gverni Could you submit the current result with the "broken" close button whenever you're ready so I can take a look and decide what would be the good solution.

**Comment by gverni** [comment]
Thanks @limonte! I pushed it in https://github.com/sweetalert2/sweetalert2-themes/pull/21/commits/a0b10ebe01b2036fe336ca6377d3be3cdaac2e12. Any help is appreciated.

**Comment by limonte** [comment]
> I've been wrestling with the close button for the past couple of days. Unfortunately when the font-size is increased, the &times; character moves slightly down and that's what you get when you hover on the close button:

The same issue seems to be happening for the default style, but it's not obvious because there's no background color on the close button.

Decreasing the `line-height` from `1.2` to `1.15` seems to fix the vertical alignment for me (Chrome and Firefox on Linux). Does it help for you as well?

**Comment by gverni** [comment]
> Decreasing the line-height from 1.2 to 1.15 seems to fix the vertical alignment for me (Chrome and Firefox on Linux). Does it help for you as well?

On chrome on macOS `line-height` seems to have no effect at all on `button`s. On the other hand It applies correctly to `div`. Maybe the _user agent stylesheet_ is different between browsers / OSs. 

[Here you can find a codepen](https://codepen.io/anon/pen/YbavmO) with the following elements: 

```html
 <div class="swal-close-manual">&times;</div>
  <button class="swal-close-manual">&times;</button>
```

For both the `swal-close-manual` is setting `line-height: 0.6;` but on my browser this is applied only to `div`: 

image

Could you have a try on linux? Or did I misunderstand your suggestion?

**Comment by gverni** [comment]
> On chrome on macOS line-height seems to have no effect at all on buttons.

@limonte I tried a different approach in 579040e. I'm here using an SVG `circle` as background image, with a position offset down (`background-position` top set at 115%). What do you think of it?

**Comment by limonte** [comment]
> @limonte I tried a different approach in 579040e. I'm here using an SVG circle as background image, with a position offset down (background-position top set at 115%). What do you think of it?

Good day @gverni!

1. the solution looks complex for its task 
2. the vertical alignment is still broken in Chrome on Linux:

image

**Comment by gverni** [comment]
> 2. the vertical alignment is still broken in Chrome on Linux:

Thanks @limonte for checking. I'll try some different approach and let you know.

**Comment by gverni** [comment]
> 1. the solution looks complex for its task

 @limonte just to check: in general, are you ok with using SVG inside CSS? I'm asking because this is what I used to style the `select` element in c655575. Let me know if you are against it in principle because I may have to use them to style other elements for material ui.

**Comment by limonte** [comment]
> @limonte just to check: in general, are you ok with using SVG inside CSS?

Yup, I'm fine with SVG inside CSS. What I don't like is so-called magic numbers, which are hard to understand and maintain:

image

**Comment by gverni** [comment]
>  What I don't like is so-called magic numbers, which are hard to understand and maintain

Fair enough @limonte 😉 I'll definitely avoid that. I'm setting up a linux machine so I'll avoid bothering you for testing (unfortunately Sauce Labs doesn't support latest version for Chrome/Firefox on Linux)

**Comment by gverni** [comment]
@limonte I added styling for `radio` element. Note that there are some _magic numbers_ (I can review them later) and also i'm not using any Swal2 SCSS variables. What do you think of this approach? 

In general for forms elements, I found difficult to style them without using background images (as in  c6555759ba208fab3c799b5713d3f94377d59fd1) or pseudo element (as in 9e342dd)

**Comment by limonte** [comment]
@gverni I totally understand difficulties you're facing, Material theme is the most complex theme to implement.

I'm alright with the PR so far, all those small details you mentioned could be improved later if needed.

**Comment by gverni** [comment]
@Yairsaenz7 note that I just pushed a fix for a bug I introduced for the radio button and that was affecting the checkboxes as well. Please pull the latest commit on this PR.

**Comment by gverni** [comment]
Sorry @limonte @Yairsaenz7 for not being active on this PR, but I had as quite hectic 10 days. I'll be on holiday for some time now, but I'll try to finalize this!

**Comment by gverni** [comment]
Couple of considerations on the last commits (be76d8e & c691cc0): 

* Based on material-UI spec, the `focus` colour should be slightly darker than the `hover`. The `active` seems to be similar color as the `focus`
* Added SCSS variable `$swal2-button-focus-background`. We may want to add this back to the main SA2 SCSS
* _Side effect_ of the commit is that the action button(s) looks darker on modal opening (since they are autofocused)

**Comment by gverni** [comment]
In order to keep alignment of the hover background, the `font-family` for close button have been changed to Arial. Below how the `serif` is rendered vs the `arial` on macOS: 

* Arial
image

* Serif
image

**Comment by gverni** [comment]
After 4 and half months, this PR is (finally) ready for review...

**Comment by gverni** [comment]
OK.. now it's ready (had to merge some critical changes from master)

**Comment by maicol07** [comment]
Is this completed? @gverni and @limonte

**Comment by gverni** [comment]
@maicol07 development is completed, but we need some more testing and feed-back. Feel free to try it out and give us your feed-back!

**Comment by maicol07** [comment]
How can I test?

**Pull request merged**
