### PR TITLE
Adding borderless style

### PR DESCRIPTION
**Pull request by Kalvisan**

### CODE REVIEW

**Comment by limonte** [comment]
Good day @Kalvisan and thank you for the PR!

Could you please check this checkbox so I can make a couple of small changes before merging?

image

**Comment by limonte** [comment]
Also, please put your name to the `author` field of `borderless/package.json`

**Comment by Kalvisan** [comment]
Are you able to access and edit repository?

**Comment by limonte** [comment]
> Are you able to access and edit repository?

Yes

**Pull request merged**
