### PR TITLE
Initial version of sweetalert2-themes

### PR DESCRIPTION
**Pull request by limonte**
Follow-up for https://github.com/sweetalert2/sweetalert2/issues/922

This is the proposal for the initial structure of this repository.

### CODE REVIEW

**Comment by acupajoe** [comment]
@limonte I was actually thinking more of a separate repo per theme. At least for the sake of separating concerns. Alternatively, we can definitely have a set of core themes. But I would imagine that adding modularity like this would also encourage other developers to produce and distribute themes.

Something like: 
`sweetalert2/minimal-theme`
`sweetalert2/dark-theme`
etc..

**Comment by zenflow** [comment]
> I was actually thinking more of a separate repo per theme.

Yes, I had the same idea in mind as @acupajoe. Having all the themes in one repo separate from the core is *more* modular [than having them in the core] but it could easily be much more modular.

---

I think we should not be committing built files (e.g. `minimal.css`) into version-control, at least in the master branch.

---

There is a lot of boilerplate in the repo for developing/linting/building/etc (naturally), especially considering how much actual code there will be. By boilerplate I mean the stuff besides the actual sass code: `gulpfile.js` & `index.html`

Especially if we are to have one theme per repo, it might be really helpful to create a package like `sweetalert2-themedesign` extracting this boilerplate into something reusable. That would 
- make the actual theme code more of the focus in each repo
- allow code sharing (between single-theme repos or multi-theme repos). Besides the obvious benefits of this, it would make it practical to create a really nice DX for people making themes, e.g. index.html can contain a comprehensive "kitchen sink" demo of all the ways a swal can appear.

---

>Something like:
>sweetalert2/minimal-theme
>sweetalert2/dark-theme

@acupajoe What would they be published as on npm? I prefer the repo name to be the same as the package name if possible. 

Also I think it would be nice to have a conventional prefix for theme package names, like `sweetalert2-theme-` (similar to `babel-preset-`, `babel-plugin-`, `gatsby-plugin-`, `gatsby-source-`, etc)

What about something like this?

- `sweetalert2/sweetalert2-theme-minimal`
- `sweetalert2/sweetalert2-theme-dark`

**Comment by acupajoe** [comment]
I would assume that it would be best to handle built files in the same way that we handle them in the main repo, yes? 

----------------------

I'd propose for this repo to be renamed and it become the `sweetalert2-theme-starter` or `sweetalert2-themedesign`

----------------------

>Also I think it would be nice to have a conventional prefix for theme package names, like sweetalert2-theme- (similar to babel-preset-, babel-plugin-, gatsby-plugin-, gatsby-source-, etc)

Yes, absolutely I think we should have a uniform prefix!

**Comment by limonte** [comment]
I believe you guys are overengineering :)

Going with the repo-per-theme way will result in an enormous number of repos and each theme repo will contain 20% of actual code and 80% of copy-pasted boilerplate code.

Here are examples of themes organization:

- Bootstrap: https://github.com/thomaspark/bootswatch/tree/master/dist
- Bulma: https://github.com/jenil/bulmaswatch
- Milligram: https://github.com/milligram/milligram-themes/tree/master/src

I hate violating DRY principle and by copy-pasting boilerplate code to each theme repo, we will do that a lot. Also, each change in boilerplate will lead to super-boring routine of making the same commit to each theme repo.

**Comment by zenflow** [comment]
@limonte Read the third section of my last comment 😉 I proposed a solution to the problems you just described. It would be useful even if we have a multi-theme repo, assuming that it will not be the *only* multi-theme repo (we want to help users with making their own custom themes right?) and if we have this then we have no reason not (that I can see) not to go with single-theme repos.

**Comment by zenflow** [comment]
> I would assume that it would be best to handle built files in the same way that we handle them in the main repo, yes?

Yeah I think so. But for starting out it might be better to not worry about the complexity of distributing to Bower users like we do in the main repo. When we go to implement this it might be a good idea to extract `release.js` from the main repo into a separate package and reuse it (or else find an already-existing package that fits our needs). This package could be a dependency of the `sweetalert2-themedesign` package I described.

**Comment by limonte** [comment]
> if we have this then we have no reason not (that I can see) not to go with single-theme repos.

- each repo will have copy-pasted code, even if it's just copy-pasted `package.json`, `LICENCE.md`, `.travis.yml`, `yarn.lock`, and `gulpfile.js` - that's already 5 files to copy-paste. From my experience the amount of copy-pasted boilerplate will grow with time.
- the organization page will be bloated with `sweetalert2-theme-*` repos.

**Comment by limonte** [comment]
> But for starting out it might be better to not worry about the complexity of distributing to Bower users like we do in the main repo.

Please do not underestimate the number of Bower users. There are still a lot of them. For the purpose of simplicity, I suggest having generated CSS files in the repo for now.

Examples of repos with CSS files in repo:

> - Bootstrap: https://github.com/thomaspark/bootswatch/tree/master/dist
> - Bulma: https://github.com/jenil/bulmaswatch
> - Milligram: https://github.com/milligram/milligram-themes/tree/master/src

**Comment by zenflow** [comment]
> each repo will have copy-pasted code, even if it's just copy-pasted package.json, LICENCE.md, .travis.yml, yarn.lock, and gulpfile.js - that's already 5 files to copy-paste. From my experience the amount of copy-pasted boilerplate will grow with time.

The amount of boilerplate code would be very little, and be a really trivial inconvenience compared to the benefit of modularity. 
- `gulpfile.js` - This would be extracted into `sweetalert2-themedesign`
- `yarn.lock` - This file is auto-generated. No need to copy-paste or worry about updating it manually
- `.travis.yml` - Ok, you might want to copy-paste (and optionally customize) this, but it's really not very much, and some users will choose not to set it up anyway. If you do set it up, it might take.. how long?.. 20-30 seconds total?
- `LICENCE.md` This file rarely ever changes (so keeping it updated is not a problem) and Github can create it for you. Even if you have to copy-paste it in manually, how long does that take? 5 seconds?
- `package.json` - `npm init` helps with this. A lot of the values would be unique to that repository, and the rest would not be very much, i.e. there will not be so many devDependencies, just `sweetalert2-themedesign`. It would be pretty short and simple.

**Comment by toverux** [comment]
I'm following the discussion since it has begun and I finally know what I'd like :)

I agree with @limonte when he says that all these copied configuration files are generating complexity, entropy, code duplications.
Having multiple packages is attractive, sexy, but has shown to be generally cumbersome when you just want to have a glance over the whole thing and make changes, or share configuration.

What is important to me though, is that we can have one npm package per theme. And it's not mandatory to have a repo per package.

So, instead of having this: https://github.com/const-io
I'd prefer: https://github.com/angular/angular. Monorepos are a thing, people blogged about them to praise their merits, and, if projects like Angular are hosting multiple packages and thousands of issues in one repo, I think we can do it as well. Create one label per theme, and voilà.

There we can share config and still separate things enough. That's a good, pragmatic compromise.

I once used [Lerna](https://github.com/lerna/lerna) for managing a monorepo, it was pretty cool.

Now we have:

`sweetalert2/sweetalert2-themes`
↳`/minimal`
↳`/glossy`
↳`/old-school`
↳`.editorconfig` `gulpfile.js` `.things.yml`

And lovely, scoped, npm packages: `@sweetalert2/theme-minimal`, `@sweetalert2/theme-glossy`, `@sweetalert2/theme-old-school`.

**Comment by limonte** [comment]
Also, please keep in mind that we are going to have SASS files in this repo. SASS means a lot of variables, a shitload of them.

Sometimes we'll need to change variables names or remove them. That will be easy search-n-replace task for all-in-one-repo (Vim ninjas can do that in less than 10 keystrokes). In case of repo-per-theme that would be a nightmare.

**Comment by acupajoe** [comment]
@limonte I will concede overengineering! Thanks for the other example repos - I think this level of modularity will fit well for our project. Thanks for convincing me otherwise!

**Comment by limonte** [comment]
Alright, this PR is ready for CR :)

The first one will be the simplest possible - for embedded iframes, something similar you can find in demos of our good competitor http://izimodal.marcelodolce.com/

**Comment by limonte** [comment]
I am going to merge this due to inactivity 😆 

I'm going to ship a couple of themes for SweetAlert2 v8 🚀

**Comment by willgdjones** [comment]
Looking forward to seeing some examples @limonte! I'm looking to create a custom theme too - so let me know if there' s anything I can do to help :).

**Pull request merged**
