### PR TITLE
Bootstrap 4 theme

### LINKED ISSUE #12: Bootstrap theme
Bootstrap seems to be an extremely popular framework.

Let's copy-paste these styles to `bootstrap-4` theme: https://getbootstrap.com/docs/4.0/components/modal/

### PR DESCRIPTION
**Pull request by REJack**
#### TODO / check
  * [x] [Base Style (Modal)](https://getbootstrap.com/docs/4.3/components/modal/#modal-components)
  * [x] [Colors](https://getbootstrap.com/docs/4.3/utilities/colors/#background-color)
  * [x] [Buttons](https://getbootstrap.com/docs/4.3/components/buttons/)
  * [x] [Text](https://getbootstrap.com/docs/4.3/components/forms/#form-controls)
  * [x] [Textarea](https://getbootstrap.com/docs/4.3/components/forms/#form-controls)
  * [x] [Toast](https://getbootstrap.com/docs/4.3/components/toasts/)
  * [x] [Select](https://getbootstrap.com/docs/4.3/components/forms/#select-menuselect)
  * [x] [Radio](https://getbootstrap.com/docs/4.3/components/forms/#radios)
  * [x] [Checkbox](https://getbootstrap.com/docs/4.3/components/forms/#checkboxes)
  * [x] [Range](https://getbootstrap.com/docs/4.3/components/forms/#range)
  * [x] [Validation message](https://getbootstrap.com/docs/4.3/components/alerts/)
  * [x] Queues
  * [x] [Toast](https://getbootstrap.com/docs/4.3/components/toasts/#basic)

Close #12

### CODE REVIEW

**Comment by limonte** [comment]
Good day @REJack and thank you for the great work so far!

I can see that the PR was inactive for some time, can we somehow help you in finalizing the PR? Will code review help at this point?

**Comment by REJack** [comment]
@limonte I stopped working on the PR while my vacation, I continue my work in the next days. 

The only thing that I'm not know if its ok with the custom variables that I've created in my PR.

**Comment by limonte** [comment]
> I stopped working on the PR while my vacation, I continue my work in the next days.

Roger, no problem, we're not in a hurry! Enjoy your vacation :palm_tree: :sun_with_face: :beach_umbrella: 

> The only thing that I'm not know if its ok with the custom variables that I've created in my PR.

Yeah, they look good to me, the readability is :1st_place_medal:

**Comment by REJack** [comment]
> Yeah, they look good to me, the readability is 🥇

Ok sweet 😄

**Comment by REJack** [comment]
@limonte I'm to 90% done with the bootstrap-4 theme, I only stuck on input[type="file"] it needs an other markup than only the input[type="file"], like this:
```html
<div class="swal2-file">
  <input type="file" class="swal2-file-input" id="swal2File">
  <label class="swal2-file-label" for="swal2File">Choose file</label>
</div>
```
and in order to replace "Choose file" with the selected file or count of selected files we would need a javascript like this but without `forEach`:

```js
var inputs = document.querySelectorAll( '.inputfile' );
Array.prototype.forEach.call( inputs, function( input )
{
	var label	 = input.nextElementSibling,
		labelVal = label.innerHTML;

	input.addEventListener( 'change', function( e )
	{
		var fileName = '';
		if( this.files && this.files.length > 1 )
			fileName = ( this.getAttribute( 'data-multiple-caption' ) || '' ).replace( '{count}', this.files.length );
		else
			fileName = e.target.value.split( '\' ).pop();

		if( fileName )
			label.querySelector( 'span' ).innerHTML = fileName;
		else
			label.innerHTML = labelVal;
	});
});
```
PS: The JS is from [this tutorial](https://tympanus.net/codrops/2015/09/15/styling-customizing-file-inputs-smart-way/)

**Comment by limonte** [comment]
@REJack let's keep things small and exclude the `input[type="file"]` from this PR and make it in another PR.

**Comment by REJack** [comment]
@limonte Ok, then I'm finish with it😄 and you can review it, there are no style for `input[type="file"]` in my PR.

**Comment by limonte** [comment]
Thanks a lot @REJack, I'll review this PR next week. Until then @gverni if you'd like to participate in review, feel free to do so, thanks!

**Comment by gverni** [comment]
> let's keep things small and exclude the input[type="file"] from this PR and make it in another PR.

FYI, we have the same problem with the material-ui theme. We may want to take a unified approach to that...

**Comment by gverni** [comment]
Hi @REJack thanks for your help with this theme! I've noticed that your SCSS triggers quite a lot of lint warnings (see more below). Do you see the same? Are you planning to work on them? 

----
```
bootstrap-4/bootstrap-4.scss
  197:47  warning  Color functions such as 'rgba' should only be used in variable declarations  no-color-literals
  218:21  warning  !important not allowed                                                       no-important
  267:22  warning  !important not allowed                                                       no-important
  273:5   warning  Expected `color`, found `box-shadow`                                         property-sort-order
  274:5   warning  Expected `box-shadow`, found `color`                                         property-sort-order
  332:8   warning  Vendor prefixes should not be used                                           no-vendor-prefixes
  339:3   warning  Pseudo-class should be nested within its parent Attribute-selector           force-pseudo-nesting
  350:6   warning  Vendor prefixes should not be used                                           no-vendor-prefixes
  363:7   warning  Expected `opacity`, found `z-index`                                          property-sort-order
  364:7   warning  Expected `z-index`, found `opacity`                                          property-sort-order
  366:7   warning  Pseudo-element should be nested within its parent Class                      force-pseudo-nesting
  366:7   warning  Nesting depth 3 greater than max of 2                                        nesting-depth
  372:7   warning  Pseudo-element should be nested within its parent Class                      force-pseudo-nesting
  372:7   warning  Nesting depth 3 greater than max of 2                                        nesting-depth
  376:7   warning  Pseudo-class should be nested within its parent Pseudo-class                 force-pseudo-nesting
  376:7   warning  Pseudo-element should be nested within its parent Class                      force-pseudo-nesting
  376:7   warning  Nesting depth 3 greater than max of 2                                        nesting-depth
  380:7   warning  Pseudo-class should be nested within its parent Pseudo-class                 force-pseudo-nesting
  380:7   warning  Pseudo-element should be nested within its parent Class                      force-pseudo-nesting
  380:7   warning  Nesting depth 3 greater than max of 2                                        nesting-depth
  387:5   warning  Pseudo-class should be nested within its parent Type-selector                force-pseudo-nesting
  387:5   warning  Pseudo-element should be nested within its parent Class                      force-pseudo-nesting
  391:5   warning  Pseudo-class should be nested within its parent Type-selector                force-pseudo-nesting
  391:5   warning  Pseudo-class should be nested within its parent Pseudo-class                 force-pseudo-nesting
  391:5   warning  Pseudo-element should be nested within its parent Class                      force-pseudo-nesting
  398:7   warning  Expected `display`, found `content`                                          property-sort-order
  399:7   warning  Expected `position`, found `display`                                         property-sort-order
  400:7   warning  Expected `top`, found `position`                                             property-sort-order
  401:7   warning  Expected `left`, found `top`                                                 property-sort-order
  402:7   warning  Expected `width`, found `left`                                               property-sort-order
  403:7   warning  Expected `height`, found `width`                                             property-sort-order
  404:7   warning  Expected `transition`, found `height`                                        property-sort-order
  405:7   warning  Expected `border`, found `transition`                                        property-sort-order
  406:7   warning  Expected `border-radius`, found `border`                                     property-sort-order
  407:7   warning  Expected `background-color`, found `border-radius`                           property-sort-order
  408:7   warning  Expected `content`, found `background-color`                                 property-sort-order
  413:7   warning  Expected `display`, found `content`                                          property-sort-order
  414:7   warning  Expected `position`, found `display`                                         property-sort-order
  415:7   warning  Expected `top`, found `position`                                             property-sort-order
  416:7   warning  Expected `left`, found `top`                                                 property-sort-order
  417:7   warning  Expected `width`, found `left`                                               property-sort-order
  418:7   warning  Expected `height`, found `width`                                             property-sort-order
  419:7   warning  Expected `transition`, found `height`                                        property-sort-order
  420:7   warning  Expected `border`, found `transition`                                        property-sort-order
  421:7   warning  Expected `background`, found `border`                                        property-sort-order
  422:7   warning  Expected `content`, found `background`                                       property-sort-order
  432:5   warning  Expected `opacity`, found `z-index`                                          property-sort-order
  433:5   warning  Expected `z-index`, found `opacity`                                          property-sort-order
  435:5   warning  Pseudo-element should be nested within its parent Class                      force-pseudo-nesting
  441:5   warning  Pseudo-element should be nested within its parent Class                      force-pseudo-nesting
  445:5   warning  Pseudo-class should be nested within its parent Pseudo-class                 force-pseudo-nesting
  445:5   warning  Pseudo-element should be nested within its parent Class                      force-pseudo-nesting
  449:5   warning  Pseudo-class should be nested within its parent Pseudo-class                 force-pseudo-nesting
  449:5   warning  Pseudo-element should be nested within its parent Class                      force-pseudo-nesting
  456:3   warning  Pseudo-class should be nested within its parent Type-selector                force-pseudo-nesting
  456:3   warning  Pseudo-element should be nested within its parent Class                      force-pseudo-nesting
  460:3   warning  Pseudo-class should be nested within its parent Type-selector                force-pseudo-nesting
  460:3   warning  Pseudo-class should be nested within its parent Pseudo-class                 force-pseudo-nesting
  460:3   warning  Pseudo-element should be nested within its parent Class                      force-pseudo-nesting
  468:7   warning  Expected `display`, found `content`                                          property-sort-order
  469:7   warning  Expected `position`, found `display`                                         property-sort-order
  470:7   warning  Expected `top`, found `position`                                             property-sort-order
  471:7   warning  Expected `left`, found `top`                                                 property-sort-order
  472:7   warning  Expected `width`, found `left`                                               property-sort-order
  473:7   warning  Expected `height`, found `width`                                             property-sort-order
  474:7   warning  Expected `transition`, found `height`                                        property-sort-order
  475:7   warning  Expected `border`, found `transition`                                        property-sort-order
  476:7   warning  Expected `background-color`, found `border`                                  property-sort-order
  477:7   warning  Expected `content`, found `background-color`                                 property-sort-order
  482:7   warning  Expected `display`, found `content`                                          property-sort-order
  483:7   warning  Expected `position`, found `display`                                         property-sort-order
  484:7   warning  Expected `top`, found `position`                                             property-sort-order
  485:7   warning  Expected `left`, found `top`                                                 property-sort-order
  486:7   warning  Expected `width`, found `left`                                               property-sort-order
  487:7   warning  Expected `height`, found `width`                                             property-sort-order
  488:7   warning  Expected `transition`, found `height`                                        property-sort-order
  489:7   warning  Expected `border`, found `transition`                                        property-sort-order
  490:7   warning  Expected `background`, found `border`                                        property-sort-order
  491:7   warning  Expected `content`, found `background`                                       property-sort-order
  496:1   warning  Type-selector should be nested within its parent Class                       force-element-nesting
  506:8   warning  Vendor prefixes should not be used                                           no-vendor-prefixes
  510:8   warning  Vendor prefixes should not be used                                           no-vendor-prefixes
  514:8   warning  Vendor prefixes should not be used                                           no-vendor-prefixes
  519:6   warning  Vendor prefixes should not be used                                           no-vendor-prefixes
  523:6   warning  Vendor prefixes should not be used                                           no-vendor-prefixes
  539:6   warning  Vendor prefixes should not be used                                           no-vendor-prefixes
  545:5   warning  Expected `color`, found `box-shadow`                                         property-sort-order
  546:5   warning  Expected `box-shadow`, found `color`                                         property-sort-order
  550:6   warning  Vendor prefixes should not be used                                           no-vendor-prefixes
  566:6   warning  Vendor prefixes should not be used                                           no-vendor-prefixes
  572:5   warning  Expected `color`, found `box-shadow`                                         property-sort-order
  573:5   warning  Expected `box-shadow`, found `color`                                         property-sort-order
  577:6   warning  Vendor prefixes should not be used                                           no-vendor-prefixes
  595:6   warning  Vendor prefixes should not be used                                           no-vendor-prefixes
  601:5   warning  Expected `color`, found `box-shadow`                                         property-sort-order
  602:5   warning  Expected `box-shadow`, found `color`                                         property-sort-order
  606:6   warning  Vendor prefixes should not be used                                           no-vendor-prefixes
  611:6   warning  Vendor prefixes should not be used                                           no-vendor-prefixes
  618:8   warning  Vendor prefixes should not be used                                           no-vendor-prefixes
  622:8   warning  Vendor prefixes should not be used                                           no-vendor-prefixes
  626:8   warning  Vendor prefixes should not be used                                           no-vendor-prefixes
  630:8   warning  Vendor prefixes should not be used                                           no-vendor-prefixes
  634:8   warning  Vendor prefixes should not be used                                           no-vendor-prefixes

✖ 103 problems (0 errors, 103 warnings)
```

**Comment by limonte** [comment]
>  I've noticed that your SCSS triggers quite a lot of lint warnings (see more below). Do you see the same? Are you planning to work on them?

I believe rebasing to master will help.

**Comment by gverni** [comment]
> I believe rebasing to master will help.

Indeed it did... no more warnings after rebasing. Thanks @limonte. 

Is the new `style-lint` more permissive? I found some of the warning with the previous configuration quite effective (e.g. `no-vendor-prefixes`, `force-pseudo-nesting`, `nesting-depth`, `force-element-nesting`). What's your view on those?

**Comment by limonte** [comment]
> Is the new style-lint default config more permissive? I found some of the warning with the previous configuration quite effective (e.g. no-vendor-prefixes, force-pseudo-nesting, nesting-depth, force-element-nesting). What's your view on those?

Agree, those would be useful. Feel free to add them to https://github.com/sweetalert2/stylelint-config

I'm quite busy this week, wouldn't be able to spend much time coding and reviewing, but I'm always ready to review small PRs during my coffee-breaks :)

**Comment by REJack** [comment]
@gverni I've fixed the issue on chrome, I faced the same issue on firefox too 😄

**Comment by REJack** [comment]
@limonte Oh dang 🤦‍♂ I've forgot the focus box-shadow on the buttons, I'll fix this later

**Comment by REJack** [comment]
@limonte I've fixed the focus on the buttons 😄

**Comment by gverni** [comment]
Thanks @REJack! Both changes look good to me. I think this is ready to be merged / published. @limonte what do you think?

**Pull request merged**
